// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineLeaveManagemntSystem.Models;

#nullable disable

namespace OnlineLeaveManagemntSystem.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineLeaveManagemntSystem.Models.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentId");

                    b.ToTable("department");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            Name = "HR"
                        },
                        new
                        {
                            DepartmentId = 2,
                            Name = "IT"
                        });
                });

            modelBuilder.Entity("OnlineLeaveManagemntSystem.Models.Entities.LeaveApplication", b =>
                {
                    b.Property<int>("LeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveId"));

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AppliedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ManagerComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LeaveId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("leaveapplication");
                });

            modelBuilder.Entity("OnlineLeaveManagemntSystem.Models.Entities.LeaveBalance", b =>
                {
                    b.Property<int>("BalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BalanceId"));

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TotalAssigned")
                        .HasColumnType("int");

                    b.Property<int>("Used")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BalanceId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("leavebalance");
                });

            modelBuilder.Entity("OnlineLeaveManagemntSystem.Models.Entities.LeaveType", b =>
                {
                    b.Property<int>("LeaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveTypeId"));

                    b.Property<int>("MaxPerYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LeaveTypeId");

                    b.ToTable("leavetype");
                });

            modelBuilder.Entity("OnlineLeaveManagemntSystem.Models.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("notification");
                });

            modelBuilder.Entity("OnlineLeaveManagemntSystem.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerId");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DateOfJoining = new DateTime(2025, 11, 26, 0, 54, 28, 574, DateTimeKind.Local).AddTicks(4793),
                            DepartmentId = 1,
                            Email = "admin@example.com",
                            FullName = "Admin User",
                            PasswordHash = "Admin@123",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            DateOfJoining = new DateTime(2025, 11, 26, 0, 54, 28, 574, DateTimeKind.Local).AddTicks(4807),
                            DepartmentId = 2,
                            Email = "manager@example.com",
                            FullName = "John Manager",
                            PasswordHash = "Manager@123",
                            Role = "Manager"
                        },
                        new
                        {
                            UserId = 3,
                            DateOfJoining = new DateTime(2025, 11, 26, 0, 54, 28, 574, DateTimeKind.Local).AddTicks(4809),
                            DepartmentId = 2,
                            Email = "employee@gmail.com",
                            FullName = "Alice Employee",
                            ManagerId = 2,
                            PasswordHash = "Employee@123",
                            Role = "Employee"
                        });
                });

            modelBuilder.Entity("OnlineLeaveManagemntSystem.Models.Entities.LeaveApplication", b =>
                {
                    b.HasOne("OnlineLeaveManagemntSystem.Models.Entities.LeaveType", "LeaveType")
                        .WithMany("LeaveApplications")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineLeaveManagemntSystem.Models.Entities.User", "User")
                        .WithMany("LeaveApplications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineLeaveManagemntSystem.Models.Entities.LeaveBalance", b =>
                {
                    b.HasOne("OnlineLeaveManagemntSystem.Models.Entities.LeaveType", "LeaveType")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineLeaveManagemntSystem.Models.Entities.User", "User")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineLeaveManagemntSystem.Models.Entities.Notification", b =>
                {
                    b.HasOne("OnlineLeaveManagemntSystem.Models.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineLeaveManagemntSystem.Models.Entities.User", b =>
                {
                    b.HasOne("OnlineLeaveManagemntSystem.Models.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineLeaveManagemntSystem.Models.Entities.User", "Manager")
                        .WithMany("EmployeesUnderManager")
                        .HasForeignKey("ManagerId");

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("OnlineLeaveManagemntSystem.Models.Entities.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("OnlineLeaveManagemntSystem.Models.Entities.LeaveType", b =>
                {
                    b.Navigation("LeaveApplications");

                    b.Navigation("LeaveBalances");
                });

            modelBuilder.Entity("OnlineLeaveManagemntSystem.Models.Entities.User", b =>
                {
                    b.Navigation("EmployeesUnderManager");

                    b.Navigation("LeaveApplications");

                    b.Navigation("LeaveBalances");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
